root = "."
tmp_dir = "tmp"
build_dir = "tmp"
binary = "tmp/main.exe"

[build]
cmd = "go build -o .\\tmp\\main.exe .\\cmd\\api\\main.go"
bin = ".\\tmp\\main.exe"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", ".git"]
delay = 1000 # ms
stop_on_error = true
log = "air.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true