// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID                          uuid.UUID      `json:"id"`
	Email                       string         `json:"email"`
	HashedPassword              string         `json:"hashedPassword"`
	UserID                      uuid.UUID      `json:"userId"`
	Status                      int32          `json:"status"`
	ResetPasswordToken          sql.NullString `json:"resetPasswordToken"`
	ResetPasswordTokenExpiresAt sql.NullTime   `json:"resetPasswordTokenExpiresAt"`
	LoginFailedAttempts         int32          `json:"loginFailedAttempts"`
	FirstFailedLoginAt          sql.NullTime   `json:"firstFailedLoginAt"`
	VerifyEmailToken            sql.NullString `json:"verifyEmailToken"`
	CreatedAt                   time.Time      `json:"createdAt"`
	UpdatedAt                   time.Time      `json:"updatedAt"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	AccountID    uuid.UUID `json:"accountId"`
	RefreshToken string    `json:"refreshToken"`
	UserAgent    string    `json:"userAgent"`
	ClientIp     string    `json:"clientIp"`
	IsBlocked    bool      `json:"isBlocked"`
	ExpiresAt    time.Time `json:"expiresAt"`
	CreatedAt    time.Time `json:"createdAt"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
