ENVIRONMENT: "development"

SERVER:
  PORT: "8080"

DATABASE:
  DRIVER: "postgres"
  SOURCE: "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
  MIGRATION_URL: "file://db/migration"

JWT:
  SECRET_KEY: "your-super-secret-key-change-this-in-production"
  TOKEN_DURATION: 1
  REFRESH_SECRET_KEY: "your-super-secret-refresh-key-change-this-in-production"
  REFRESH_TOKEN_DURATION: 2

LOG:
  LEVEL: "debug"
  PATH: "./logs"